version: "3.9"

services:
  app:
    image: python-tattoostylegan2:local-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    # command: python3 ./instaScrapper.py
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    volumes:
      - .:/app:delegated
      - ~/dev/jd-images:/app/raw-images:delegated
    networks:
      - default